import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import kyotoLogo from "../src/logo.webp";
import discordFav from "../src/discord.png";
import twitterFav from "../src/twitter.png";
import instagramFav from "../src/instagram.png";
import youtubeFav from "../src/youtube.png";
import linkedinFav from "../src/linkedin.png";
import telegramFav from "../src/telegram-plane.png";
//import backgroundImage from '../src/background.svg'
import logoGreen from "../src/logo-green.webp";
import planeta from "../src/planeta.png";
import monedas from "../src/monedas.webp";
import logoProtocol from "../src/logo-protocol.webp";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kyoto S wap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-green-700 h-20 w-screen flex flex-row">
        <div className="h-full float-left">
          <Link href="/">
            <Image
              className="px-8 py-5"
              src={kyotoLogo}
              alt="kyoto Logo"
              height={60}
            />
          </Link>
        </div>

        <div className="h-full">
          <nav className="h-10 m-5">
            <ul className="flex flex-row gap-1  text-center">
              <li className="dropdown dropdown-hover w-24 h-10 border-0  rounded-full hover:shadow hover:bg-green-600">
                <div className=" w-full h-full ">
                  <label tabIndex={0} className="text-2xl text-white">
                    Trade
                  </label>
                </div>
                <ul className="dropdown-content menu p-2 shadow bg-primary border-0 rounded-box w-24 text-white text-xl ">
                  <li className="hover:bg-green-600">
                    <Link href="/swap">Swap</Link>
                  </li>
                  <li className="hover:bg-green-600">Liquidity</li>
                  <li className="hover:bg-green-600">OTC</li>
                </ul>
              </li>
              <li className="dropdown dropdown-hover w-24 h-10 border-0  rounded-full hover:shadow hover:bg-green-600">
                <div className=" w-full h-full ">
                  <label tabIndex={0} className="text-2xl text-white ">
                    Earn
                  </label>
                </div>
                <ul className="dropdown-content menu p-2 shadow bg-primary rounded-box w-24 text-white text-xl">
                  <li className="hover:bg-green-600">Farms</li>
                  <li className="hover:bg-green-600">Pools</li>
                  <li className="hover:bg-green-600">DV</li>
                </ul>
              </li>
              <li className="dropdown dropdown-hover w-24 h-10 border-0  rounded-full hover:shadow hover:bg-green-600">
                <div className=" w-full h-full ">
                  <label tabIndex={0} className="text-2xl text-white ">
                    Win
                  </label>
                </div>
                <ul className="dropdown-content menu p-2 shadow bg-primary rounded-box w-24 text-white text-xl ">
                  <li className="hover:bg-green-600">Rafflez</li>
                </ul>
              </li>
              <li className="w-24 h-10 border-0  rounded-full hover:shadow hover:bg-green-600">
                <div className=" w-full h-full ">
                  <label tabIndex={0} className="text-2xl text-white ">
                    Impact
                  </label>
                </div>
              </li>
              <li className="w-24 h-10 border-0  rounded-full hover:shadow hover:bg-green-600">
                <div className=" w-full h-full ">
                  <label tabIndex={0} className="text-2xl text-white ">
                    Bridge
                  </label>
                </div>
              </li>
              <li className="dropdown dropdown-hover w-24 h-10 border-0  rounded-full hover:shadow hover:bg-green-600">
                <div className=" w-full h-full ">
                  <label tabIndex={0} className="text-2xl text-white ">
                    Info
                  </label>
                </div>
                <ul className="dropdown-content menu p-2 shadow bg-primary rounded-box w-24 text-white text-xl">
                  <li className="hover:bg-green-600">Docs</li>
                </ul>
              </li>
              <li className="w-24 h-10 border-0  rounded-full hover:shadow hover:bg-green-600">
                <div className=" w-full h-full ">
                  <label tabIndex={0} className="text-2xl text-white ">
                    Launch
                  </label>
                </div>
              </li>
            </ul>
          </nav>
        </div>

        <div className="h-full flex flex-row ml-auto">
          <div className="h-20 pt-4 float-right">
            <button className="border-2 text-white border-yellow-600 rounded-full h-12 w-28 float-right">
              <b>Vault</b>
            </button>
          </div>
          <div className="h-20 pt-4 float-right ml-3">
            <button className="border-2 text-white border-yellow-600 rounded-full h-12 w-28 float-right">
              <b>Price</b>
            </button>
          </div>
          <div className="h-20 pt-4 float-right mx-3">
            <button className="border-2 border-yellow-600 bg-yellow-600 rounded-full h-12 w-44 float-right">
              Connect Wallet
            </button>
          </div>
        </div>
      </header>
      <main className="bg-green-700 h-screen">
        <div className="bg-green-300 h-18">
          <nav className="flex flex-row text-2xl text-green-700 justify-center">
            <div className="border-b-2  border-yellow-300 p-4">
              <p>Swap</p>
            </div>
            <div className="border-b-2 border-white p-4">
              <p>Liquidity</p>
            </div>
          </nav>
        </div>

        <div className="flex flex-row">
          <div className="h-screen w-10">
            {/* social media bar*/}
            <div className="mt-80">
              <div className="">
                <Image
                  className="px-1 mt-2"
                  src={twitterFav}
                  alt="Twitter"
                  height={30}
                />
              </div>
              <div>
                <Image
                  className="px-1 mt-2"
                  src={instagramFav}
                  alt="Intagram"
                  height={30}
                />
              </div>
              <div>
                <Image
                  className="px-1 mt-2"
                  src={telegramFav}
                  alt="Telegram"
                  height={30}
                />
              </div>
              <div>
                <Image
                  className="px-1 mt-2"
                  src={youtubeFav}
                  alt="YouTube"
                  height={30}
                />
              </div>
              <div>
                <Image
                  className="px-1 mt-2"
                  src={discordFav}
                  alt="Discord"
                  height={30}
                />
              </div>
              <div>
                <Image
                  className="px-1 mt-2"
                  src={linkedinFav}
                  alt="LinkedIn"
                  height={30}
                />
              </div>
            </div>
          </div>
          <div className="ml-[38%]">
            <h1 className="text-center text-7xl m-10 mt-20">
              <b>SWAP</b>
            </h1>
            <div className="flex flex-col bg-green-300 rounded-2xl text-green-700">
              <div className="flex flex-row m-2">
                <div className="w-2/4 m-2">
                  <p>
                    <b>SWAP</b>
                  </p>
                </div>
                <div className="w-2/4 text-right">
                  <button className="px-2 bg-green-100 rounded-full m-1 my-2">
                    S
                  </button>
                  <button className="px-2 bg-green-100 rounded-full m-1 my-2">
                    A
                  </button>
                  <button className="px-2 bg-green-100 rounded-full m-1 my-2">
                    R
                  </button>
                </div>
              </div>
              <p className="w-[100%] text-sm text-right -ml-2">
                Trade tokens in an instant.
              </p>
              <div>
                <div className="flex flex-row pt-2 px-2">
                  <label
                    className="bg-green-100 p-2 px-4 rounded-t-xl"
                    htmlFor=""
                  >
                    WBNB
                  </label>
                  <p className="w-full text-right text-white">Balance: 0.00</p>
                </div>
                <div className="px-2">
                  <input
                    className="bg-green-100 p-1 rounded-b-xl rounded-r-xl w-full h-16"
                    type="number"
                  />
                </div>
                <div className="my-3 mx-2 text-sm">
                  <span className="bg-green-100 rounded-3xl px-6 mx-2">
                    25%
                  </span>
                  <span className="bg-green-100 rounded-3xl px-6 mx-2">
                    50%
                  </span>
                  <span className="bg-green-100 rounded-3xl px-6 mx-2">
                    75%
                  </span>
                  <span className="bg-green-100 rounded-3xl px-6 mx-2">
                    MAX
                  </span>
                </div>
                <div className="flex flex-row pt-2 px-2">
                  <label
                    className="bg-green-100 p-2 px-4 rounded-t-xl"
                    htmlFor=""
                  >
                    WBNB
                  </label>
                  <p className="w-full text-right text-white">Balance: 0.00</p>
                </div>
                <div className="px-2 mb-2">
                  <input
                    className="bg-green-100 p-1 rounded-b-xl rounded-r-xl w-full h-16"
                    type="number"
                  />
                </div>
                <div className="text-green-700 bg-gray-300 rounded-full text-center py-2 mx-2 my-4">
                  <label htmlFor="">
                    <b>SWAP</b>
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className="h-screen bg-white">
        <div className="text-center text-green-700">
          <div className="pt-36 ml-[43%]">
            <Image src={logoGreen} alt={"logo"} height={80} />
          </div>
          <p className="text-6xl py-4">
            <b>HELP FIGHT</b>
          </p>
          <p className="text-6xl py-4">
            <b>CLIMATE CHANGE</b>
          </p>
          <p className="text-4xl text-green-300">
            <i>
              <b>PASSIVELY</b>
            </i>
          </p>
        </div>
        <div className="mt-60">
          <hr className="w-[80%] ml-[10%] border border-green-700 mb-8" />
          <div className="flex flex-row gap-60 mx-20">
            <div className="">
              <div className="pb-8">
                <Image src={logoGreen} alt={"logo"} height={50} />
              </div>
              <div className="bg-green-700 rounded-full p-2 px-4">
                <label htmlFor="" className="text-yellow-300 text-3xl">
                  <b>BUY KSWAP</b>
                </label>
              </div>
            </div>
            <div className="text-m text-green-700">
              <p className="mb-1">
                <b>ABOUT</b>
              </p>
              <p>CONTACT</p>
              <p>BRAND</p>
              <p>BLOG</p>
              <p>COMMUNITY</p>
            </div>
            <div className="text-m text-green-700">
              <p className="mb-1">
                <b>HELP</b>
              </p>
              <p>CUSTOMER SUPPORT</p>
              <p>TROUBLESHOOTING</p>
              <p>GUIDES</p>
            </div>
            <div className="text-m text-green-700">
              <p className="mb-1">
                <b>DEVELOPERS</b>
              </p>
              <p>DOCUMENTATION</p>
              <p>BUG BOUNTY</p>
              <p>AUDITS</p>
              <p>CAREERS</p>
            </div>
            <div>
              <div>
                <div className="flex flex-row">
                  <div className="">
                    <Image
                      className="px-1 mt-2"
                      src={twitterFav}
                      alt="Twitter"
                      height={30}
                    />
                  </div>
                  <div>
                    <Image
                      className="px-1 mt-2"
                      src={instagramFav}
                      alt="Intagram"
                      height={30}
                    />
                  </div>
                  <div>
                    <Image
                      className="px-1 mt-2"
                      src={telegramFav}
                      alt="Telegram"
                      height={30}
                    />
                  </div>
                  <div>
                    <Image
                      className="px-1 mt-2"
                      src={youtubeFav}
                      alt="YouTube"
                      height={30}
                    />
                  </div>
                  <div>
                    <Image
                      className="px-1 mt-2"
                      src={discordFav}
                      alt="Discord"
                      height={30}
                    />
                  </div>
                  <div>
                    <Image
                      className="px-1 mt-2"
                      src={linkedinFav}
                      alt="LinkedIn"
                      height={30}
                    />
                  </div>
                </div>
              </div>
              <div>
                <div className="pt-14">
                  <Image src={logoProtocol} alt={"logoProtocol"} height={40} />
                </div>
              </div>
            </div>
          </div>
          <hr className="w-[80%] ml-[10%] border border-green-700 mt-8" />
        </div>
      </footer>
    </>
  );
}
